/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ali_rice;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author SMASH
 */

public class Receiveable extends javax.swing.JFrame {

    /**
     * Creates new form Payable
     */
    String dbURL=null;
    public Receiveable() {
        initComponents();
       
        init();
    }
    String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url="jdbc:sqlserver://localhost:1433;databaseName=AliDB";
    String user="l134088";
    String pass="sofabulous12";

    private void init()
    {
         try
         {
                Class.forName(driver);
                Connection con=DriverManager.getConnection(url,user,pass);
                // Step 2.B: Creating JDBC Statement 
                Statement stmt = con.createStatement();
                String query;
                query= "SELECT distinct(name) FROM Customer_table";
                PreparedStatement pst=con.prepareStatement(query);

                
                ResultSet rs = pst.executeQuery();

                while(rs.next()){
                String s=rs.getString(1);
                namescombo.addItem(s);
            }   
                   
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Sql exception in processing article name");
                JOptionPane.showMessageDialog(null, ex);
               
            }
            catch(Exception e)
            {
                 JOptionPane.showMessageDialog(null, e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        namescombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        debtfield = new javax.swing.JTextField();
        debitfield = new javax.swing.JLabel();
        amountfield = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Payable");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        namescombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namescombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        namescombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namescomboActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Supplier Name");

        debitfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        debitfield.setText("Debt");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Clear this Amount");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Receiveable");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(debitfield, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namescombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(debtfield)
                    .addComponent(amountfield, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namescombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(debtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debitfield))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    Float originalDebt;
    private void namescomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namescomboActionPerformed
        // TODO add your handling code here:
        
         try
         {
                Class.forName(driver);
                Connection con=DriverManager.getConnection(url,user,pass);
                // Step 2.B: Creating JDBC Statement 
                Statement stmt = con.createStatement();
                String query;
                query = ("SELECT due FROM Customer_table WHERE name=?");
                PreparedStatement pst=con.prepareStatement(query);
                pst.setString(1, namescombo.getSelectedItem().toString());
                ResultSet rs = pst.executeQuery();
                float n;
                if(rs.next()){
                    n=rs.getInt(1);
                    
                    debtfield.setText(Float.toString(n));
                }
                
                if(Float.parseFloat(debtfield.getText()) >0)
                {
             
                    debitfield.setText("Credit");
        
                }
                else
                {
                    debitfield.setText("Debit");
                }
                     
            
         }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.toString() );                    
        }
        
    }//GEN-LAST:event_namescomboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
         {
                Class.forName(driver);
                Connection con=DriverManager.getConnection(url,user,pass);
                // Step 2.B: Creating JDBC Statement 
                Statement stmt = con.createStatement();
                String query;
                query = ("UPDATE Customer_table  SET [due]=[due] - ? WHERE name=?");
                PreparedStatement pst=con.prepareStatement(query);
                pst.setFloat(1, Float.parseFloat(amountfield.getText()));
                pst.setString(2, namescombo.getSelectedItem().toString());
               
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Reduced Successfully" );
//                amountfield.setText("");
                
                query = ("SELECT due FROM Customer_table WHERE name=?");
                pst=con.prepareStatement(query);
                pst.setString(1, namescombo.getSelectedItem().toString());
                ResultSet rs = pst.executeQuery();

                if(rs.next()){
                    float n=rs.getInt(1);
                    debtfield.setText(Float.toString(n));
                }
                originalDebt =Float.parseFloat(debtfield.getText());
                
         }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.toString() );                    
        }
        
        try{
            ResultSet rs=null;
            Class.forName(driver);
            Connection con=DriverManager.getConnection(url,user,pass);
            // Step 2.B: Creating JDBC Statement 
            Statement stmt = con.createStatement();
            String query;
            query= "INSERT INTO Dues(date,name,dues_paid,type,calculateTotal)VALUES(?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(query);

            pst.setTimestamp(1,new java.sql.Timestamp(System.currentTimeMillis()));
            pst.setString(2, namescombo.getSelectedItem().toString());
            pst.setString(3, amountfield.getText());
            pst.setString(4, "Seller");
            pst.setString(5, debtfield.getText());

            pst.execute();
            
            //Update cash flow
            query = ("UPDATE cash_table SET cash=cash + ? where type=?");
            pst = con.prepareStatement(query);

            // pst.setInt(1, id);
            pst.setFloat(1, Float.parseFloat(amountfield.getText()));
            pst.setString(2, "cash");

            pst.execute();

            // finish cash flow
        
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
//        Statement stmt=null;
//        ResultSet rs=null;
//        Connection conn=null;
//       //  Date date = formatter.parse(jComboBox2.getSelectedItem().toString());
//                 
//       DateFormat dateFormat = new SimpleDateFormat("YYYY-MMM-dd");
//              Date date = new Date();
//              String d=dateFormat.format(date);
//        int n=Integer.parseInt(amountfield.getText());
//         try{
//              
//                conn = DriverManager.getConnection(dbURL); 
//                stmt = conn.createStatement();
//                //  query= "UPDATE  Product_details_table SET remaining_weight = ?  WHERE id = ?";
//
//                stmt.executeUpdate("UPDATE Supplier_table  SET [dues]=[dues] - ? WHERE name=?");
//                PreparedStatement pst=con.prepareStatement(query);
//
//            pst.setFloat(1, updateRemainingweightValue);
//            pst.setFloat(2, billNo);
//            
//            pst.executeUpdate();
//                JOptionPane.showMessageDialog(this,"Debt Reduced Successfully" );
//                 stmt.executeUpdate("INSERT INTO Dues(Datess,C_Name,Dues_paid)VALUES('"+d+"','"+namescombo.getSelectedItem().toString()+"','"+Integer.parseInt(debtfield.getText())+"')");
//               
//                debtfield.setText("");
//                amountfield.setText("");
//                
//         }
//         catch(SQLException e)
//        {
//            JOptionPane.showMessageDialog(this,e.toString() );                    
//        }

    
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receiveable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receiveable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receiveable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receiveable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receiveable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountfield;
    private javax.swing.JLabel debitfield;
    private javax.swing.JTextField debtfield;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> namescombo;
    // End of variables declaration//GEN-END:variables
}
