/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ali_rice;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.SwingConstants;

/**
 *
 * @author Naffah Amin
 */
public class SimpleBill extends javax.swing.JFrame {

    /**
     * Creates new form SimpleBill
     */
    String article, name, weight, amount, bags, rate;
    Float bori_amount;
    
    Timestamp currentDate = new java.sql.Timestamp(System.currentTimeMillis());
    Date current = new Date(currentDate.getTime());
        
    
    private void setEnglish() {
        date1.setText(current.toString());
        customer1.setText(name);
        articlename1.setText(article);
        amountLabel1.setText("" + bori_amount);
        weightLabel1.setText(weight);
        sacksLabel1.setText(bags);
        rateLabel1.setText(rate);
        totalLabel1.setText(amount);
        
        engPanel.setVisible(true);
        
        urduPanel.setVisible(false);
    }
    
    private void setUrdu() {
        engPanel.setVisible(false);
        
        urduPanel.setVisible(true);
    }
    
    public SimpleBill(String article, String name, String weight, String amount, String rate, String bags) {
        this.setTitle("Bill");
        initComponents();
        
        this.article = article;
        this.name = name;
        this.weight = weight;
        this.amount = amount;
        this.rate = rate;
        this.bags = bags;
        
        bori_amount = Float.parseFloat(rate) * Float.parseFloat(weight);
        
        setEnglish();
    }
    
    public SimpleBill() {
        this.setTitle("Bill");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        date1 = new javax.swing.JLabel();
        customer1 = new javax.swing.JLabel();
        articlename1 = new javax.swing.JLabel();
        weightLabel1 = new javax.swing.JLabel();
        amountLabel1 = new javax.swing.JLabel();
        urduPanel = new javax.swing.JPanel();
        weightLabel2 = new javax.swing.JLabel();
        customer2 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        amountLabel2 = new javax.swing.JLabel();
        articlename2 = new javax.swing.JLabel();
        sacksLabel2 = new javax.swing.JLabel();
        rateLabel2 = new javax.swing.JLabel();
        amountLabel4 = new javax.swing.JLabel();
        sacksLabel1 = new javax.swing.JLabel();
        rateLabel1 = new javax.swing.JLabel();
        engPanel = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        customer = new javax.swing.JLabel();
        articlename = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        sacksLabel = new javax.swing.JLabel();
        rateLabel = new javax.swing.JLabel();
        amountLabel3 = new javax.swing.JLabel();
        totalLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        urduBtn = new javax.swing.JButton();
        englishBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        date1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        date1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        date1.setText("1234");

        customer1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        customer1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customer1.setText("customer");
        customer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer1MouseClicked(evt);
            }
        });

        articlename1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        articlename1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        articlename1.setText("article");

        weightLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        weightLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        weightLabel1.setText("weight");

        amountLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        amountLabel1.setText("amount");

        weightLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        weightLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        weightLabel2.setText("وزن");

        customer2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        customer2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customer2.setText("نام");
        customer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer2MouseClicked(evt);
            }
        });

        date2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        date2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date2.setText("تاریخ");

        amountLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amountLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        amountLabel2.setText("بوری رقم");

        articlename2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        articlename2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        articlename2.setText("پروڈکٹ");

        sacksLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sacksLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sacksLabel2.setText("بوریاں");

        rateLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rateLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rateLabel2.setText("ریٹ");

        amountLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amountLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        amountLabel4.setText("کل رقم");

        javax.swing.GroupLayout urduPanelLayout = new javax.swing.GroupLayout(urduPanel);
        urduPanel.setLayout(urduPanelLayout);
        urduPanelLayout.setHorizontalGroup(
            urduPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urduPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(urduPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customer2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(articlename2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(amountLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sacksLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rateLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(amountLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        urduPanelLayout.setVerticalGroup(
            urduPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urduPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date2)
                .addGap(40, 40, 40)
                .addComponent(customer2)
                .addGap(30, 30, 30)
                .addComponent(articlename2)
                .addGap(34, 34, 34)
                .addComponent(sacksLabel2)
                .addGap(34, 34, 34)
                .addComponent(weightLabel2)
                .addGap(38, 38, 38)
                .addComponent(rateLabel2)
                .addGap(30, 30, 30)
                .addComponent(amountLabel2)
                .addGap(27, 27, 27)
                .addComponent(amountLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sacksLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sacksLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sacksLabel1.setText("sacks");

        rateLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rateLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rateLabel1.setText("rate");

        date.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        date.setText("Date:");

        customer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        customer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customer.setText("Customer:");
        customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerMouseClicked(evt);
            }
        });

        articlename.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        articlename.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        articlename.setText("Article:");

        weightLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        weightLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        weightLabel.setText("Weight (KG):");

        amountLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amountLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        amountLabel.setText("Amount:");

        sacksLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sacksLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sacksLabel.setText("Bags:");

        rateLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rateLabel.setText("Rate:");

        amountLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amountLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        amountLabel3.setText("Total:");

        javax.swing.GroupLayout engPanelLayout = new javax.swing.GroupLayout(engPanel);
        engPanel.setLayout(engPanelLayout);
        engPanelLayout.setHorizontalGroup(
            engPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(engPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(engPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date)
                    .addComponent(articlename)
                    .addComponent(customer)
                    .addComponent(amountLabel)
                    .addComponent(sacksLabel)
                    .addComponent(rateLabel)
                    .addComponent(weightLabel)
                    .addComponent(amountLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        engPanelLayout.setVerticalGroup(
            engPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(engPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(date)
                .addGap(29, 29, 29)
                .addComponent(customer)
                .addGap(37, 37, 37)
                .addComponent(articlename)
                .addGap(27, 27, 27)
                .addComponent(sacksLabel)
                .addGap(30, 30, 30)
                .addComponent(weightLabel)
                .addGap(39, 39, 39)
                .addComponent(rateLabel)
                .addGap(29, 29, 29)
                .addComponent(amountLabel)
                .addGap(28, 28, 28)
                .addComponent(amountLabel3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        totalLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalLabel1.setText("total");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("MUSTAFA RICE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(160, 160, 160))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(engPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(articlename1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(weightLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amountLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sacksLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rateLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(urduPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(date1)
                        .addGap(34, 34, 34)
                        .addComponent(customer1)
                        .addGap(44, 44, 44)
                        .addComponent(articlename1)
                        .addGap(34, 34, 34)
                        .addComponent(sacksLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(weightLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(rateLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(amountLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(totalLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(engPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(urduPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        urduBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        urduBtn.setText("Urdu");
        urduBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urduBtnActionPerformed(evt);
            }
        });

        englishBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        englishBtn.setText("English");
        englishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishBtnActionPerformed(evt);
            }
        });

        printBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(englishBtn)
                .addGap(35, 35, 35)
                .addComponent(urduBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urduBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(englishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void englishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishBtnActionPerformed
        // TODO add your handling code here:
        setEnglish();
    }//GEN-LAST:event_englishBtnActionPerformed

    private void urduBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urduBtnActionPerformed
        // TODO add your handling code here:
        setUrdu();
    }//GEN-LAST:event_urduBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        
        job.setPrintable(new Printable(){
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.5, 0.5);
                
                jPanel1.paint(g2);
                
                return Printable.PAGE_EXISTS;
            }
        });
        
        boolean ok = job.printDialog();
        if (ok) {
            try {
                job.print();
            } catch (PrinterException ex) {
            }
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_customerMouseClicked

    private void customer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_customer1MouseClicked

    private void customer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_customer2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel amountLabel1;
    private javax.swing.JLabel amountLabel2;
    private javax.swing.JLabel amountLabel3;
    private javax.swing.JLabel amountLabel4;
    private javax.swing.JLabel articlename;
    private javax.swing.JLabel articlename1;
    private javax.swing.JLabel articlename2;
    private javax.swing.JLabel customer;
    private javax.swing.JLabel customer1;
    private javax.swing.JLabel customer2;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JPanel engPanel;
    private javax.swing.JButton englishBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JLabel rateLabel1;
    private javax.swing.JLabel rateLabel2;
    private javax.swing.JLabel sacksLabel;
    private javax.swing.JLabel sacksLabel1;
    private javax.swing.JLabel sacksLabel2;
    private javax.swing.JLabel totalLabel1;
    private javax.swing.JButton urduBtn;
    private javax.swing.JPanel urduPanel;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JLabel weightLabel1;
    private javax.swing.JLabel weightLabel2;
    // End of variables declaration//GEN-END:variables
}
